allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': false
  '@google/genai': false
  electron-winstaller: false
  koffi: false
  node-pty: false
  protobufjs: false

nodeLinker: hoisted
autoInstallPeers: true
patchedDependencies:
  '@deepseek-ai/dsh-sandbox@0.1.5-rc.2': patches/@deepseek-ai__dsh-sandbox@0.1.5-rc.2.patch
